---
- name: Configure Docker on test2-server
  hosts: test2-server
  become: true
  tasks :
  - name: updating apt
    command: sudo apt-get update

  - name: Install Docker
    command: sudo apt-get install -y docker.io

  - name: Start Docker Service
    command: sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8096:8082  shabana4195/healthcare-project-demo:1.0
